name: run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run
      env:
        IP_ASSIGNMENT: ${{ secrets.IP_ASSIGNMENT }}
        ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
        ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      run: |
        sudo bash ./run.sh
